#Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

##Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [2]:
import numpy as np
empty_array= np.empty((2,2))
empty_array.shape

(2, 2)

2.Initialize an all one array with size 4X2.

In [3]:
import numpy as np
ones_array = np.ones((4, 2))
print(ones_array)
print("The size of array is",ones_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
The size of array is (4, 2)


3.Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [4]:
import numpy as np
new_array=np.full((2,2),fill_value=1)
print(new_array)

[[1 1]
 [1 1]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [5]:
import numpy as np
existing_array= np.zeros((2,2))
A1=np.zeros_like(existing_array)
print(A1)

[[0. 0.]
 [0. 0.]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [6]:
existing_array= np.ones((2,2))
B=np.ones_like(existing_array)
B

array([[1., 1.],
       [1., 1.]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [7]:
new_list=[1,2,3,4]
a=np.array(new_list)
a


array([1, 2, 3, 4])

##Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [8]:
a= np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2.Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [9]:
a= np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [10]:
a= np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [11]:
a= np.random.random(30)
m= a.mean()
print("The array is",a)
print("the mean is", m)

The array is [0.93796548 0.15471716 0.96804599 0.13784032 0.51885813 0.54182608
 0.77751122 0.34848903 0.72023753 0.0692735  0.09754872 0.82108085
 0.18673041 0.82145757 0.58891886 0.32041006 0.30672943 0.25827329
 0.93264336 0.89645558 0.45851579 0.49949989 0.07349113 0.85855561
 0.38959867 0.30823479 0.4076786  0.33856389 0.30930032 0.85754252]
the mean is 0.49686645899954685


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [12]:
import numpy as np

a= np.random.random(100).reshape(10,10)
minimum=a.min()
maximum=a.max()
print("The array ",a)
print("The minimum value is",minimum);
print("The maximum value is",maximum);

The array  [[0.6561475  0.83087603 0.30792485 0.81315367 0.92919805 0.23544663
  0.50673689 0.6406218  0.46239135 0.76656348]
 [0.54980375 0.19352085 0.05869016 0.58976111 0.06730125 0.02667194
  0.6646693  0.97541321 0.61994528 0.25478876]
 [0.71381331 0.53560114 0.3655155  0.82686724 0.27437475 0.01554475
  0.79014279 0.80300926 0.32815162 0.9966201 ]
 [0.47493175 0.7695851  0.41850181 0.7446765  0.49271806 0.37258232
  0.83658068 0.20137061 0.755209   0.64215873]
 [0.52239567 0.67963388 0.35259989 0.14681792 0.09287223 0.54728085
  0.06325304 0.77840661 0.18273869 0.38039554]
 [0.83189325 0.88598237 0.53705333 0.28400332 0.71929738 0.49618822
  0.12125127 0.76397658 0.31946804 0.49135595]
 [0.39614935 0.35437733 0.64020643 0.08506973 0.13099069 0.13306568
  0.5439412  0.57925878 0.94275101 0.63691116]
 [0.11565319 0.78368676 0.01622935 0.88766109 0.96424747 0.93098799
  0.06865703 0.69615752 0.95208389 0.54719317]
 [0.58025632 0.9212986  0.88737974 0.84200604 0.08739968 0.93231618
 

6. Create a zero array of size 10 and replace 5th element with 1.

In [13]:
import numpy as np
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [14]:
arr = [1,2,0,0,4,0]
arr1=arr[::-1]
print(arr1)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [15]:
import numpy as np

arr= np.zeros((5,5))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [16]:
import numpy as np

arr= np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

##Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.

2. Subtract the two array.

3. Multiply the array with any integers of your choice.

4. Find the square of each element of the array.

5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [17]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_xy=x+y
print("The addition of x and y :", add_xy)

sub_xy=x-y
print("The subtraction of x and y :", sub_xy)

mul_x = x * 2
print("Multiplication of x by 2:", mul_x)

square_x = x**2
print("Square of each element in x:", square_x)



The addition of x and y : [[ 6  8]
 [10 13]]
The subtraction of x and y : [[-4 -4]
 [-4 -3]]
Multiplication of x by 2: [[ 2  4]
 [ 6 10]]
Square of each element in x: [[ 1  4]
 [ 9 25]]


In [18]:
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)
dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)
dot_xy = np.dot(x, y)
print("Dot product of x and y:", dot_xy)

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


In [19]:
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("Concatenate x and y along rows:", concat_xy_row)
print("Concatenate v and w along columns:", concat_vw_col)

Concatenate x and y along rows: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns: [[ 9 10]
 [11 12]]


In [ ]:
#concat_xv_row = np.concatenate((x, v), axis=0)
#print(concat_xv_row)
#concat_xv_column= np.concatenate((x, v), axis=1)
#print(concat_xv_column)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

##Problem - 4: Matrix Operations:

For the following arrays:


A = np.array([[3,4],[7,8]])

and

B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1. Prove A.(A)^−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)^T = B^T*A^T.


In [23]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
#1
A_inv = np.linalg.inv(A)
identity_matrix=np.dot(A,A_inv)
print("A*A^-1=I:\n" , identity_matrix)

#2.
AB=np.dot(A,B)
BA=np.dot(B,A)
AB_BA = not np.array_equal(AB,BA)
print("AB is not equals to BA",AB_BA)

#3
AB_T =np.transpose(AB)
BT_AT =np.dot(np.transpose(B),np.transpose(A))
AB_T_BT_AT=np.array_equal(AB_T,BT_AT)
print( "(AB)^T =B^T *A^T:",AB_T_BT_AT )


A*A^-1=I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB is not equals to BA True
(AB)^T =B^T *A^T: True


In [24]:
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])

# Solving using np.linalg.inv
solution = np.dot(np.linalg.inv(coefficients), constants)
print("\nSolution of the system of linear equations:\n", solution)


Solution of the system of linear equations:
 [ 2.  1. -2.]
